---
deployment:
  tasks:
    - export DEPLOYPATH=/home/np16374/machines/arabicart
    - /bin/cd ..
    - /bin/rsync -avr --exclude='arabicart/.git' arabicart ../machines
    - /bin/cd arabicart
    - /bin/cd